#############################################
# Browsie can handle multiple arguements all
# that is required is that each email have
# corresponding password, and that each
# argument have a space followed by a '-'
# followed by another space, then the argument
#
# If you don't have one or both of these accounts
# delete out the keywords and arguments alltogether.
#############################################
LOGIN: 
 - first.last@usaa.com 
PASSWORD: 
 - your_lynda_password
FIRST_NAME:
 - your_first_name
